[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
